vich_uploader:
    db_driver: orm


    mappings:
        article_cover:
            uri_prefix: /images/article/cover
            upload_destination: '%kernel.project_dir%/public/images/article/cover'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
